In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 

In [41]:
df=pd.read_csv("hp_data.csv")
df

Unnamed: 0     price                 place                 built  sqft  \
0           1341   6300000            BTM Layout  Super built-up  Area  1450   
1           2126  11500000             Yelahanka  Super built-up  Area  2190   
2            816   3800000            Whitefield  Super built-up  Area  1019   
3           2708  10500000            Ambalipura  Super built-up  Area  1857   
4           1041  11500000             Yelahanka  Super built-up  Area  2190   
...          ...       ...                   ...                   ...   ...   
3495         636   3800000            Whitefield  Super built-up  Area  1019   
3496        1664   6300000            BTM Layout  Super built-up  Area  1450   
3497        1252   7350000        Yelachenahalli  Super built-up  Area  1330   
3498         903   4800000  Abbaiah Reddy Layout        Built-up  Area  1200   
3499        2183   3800000            Whitefield  Super built-up  Area  1019   

        sale  yearsOld  floor  totalFloor  bhk  
0     Resale         5      1           4    1  
1     Resale         5      3           5    3  
2     Resale         1      2           5    2  
3     Resale        15      4           5    4  
4     Resale         5      3           5    3  
...      ...       ...    ...         ...  ...  
3495  Resale         1      2           5    2  
3496  Resale         5      1           4    1  
3497  Resale        10      1           4    1  
3498  Resale        10      1           4    1  
3499  Resale         1      2           5    2  

[3500 rows x 10 columns]

In [42]:
df.shape

(3500, 10)

In [43]:
df.size

35000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  3500 non-null   int64 
 1   price       3500 non-null   int64 
 2   place       3500 non-null   object
 3   built       3500 non-null   object
 4   sqft        3500 non-null   int64 
 5   sale        3500 non-null   object
 6   yearsOld    3500 non-null   int64 
 7   floor       3500 non-null   int64 
 8   totalFloor  3500 non-null   int64 
 9   bhk         3500 non-null   int64 
dtypes: int64(7), object(3)
memory usage: 273.6+ KB


In [45]:
df.describe()

Unnamed: 0         price         sqft     yearsOld        floor  \
count  3500.000000  3.500000e+03  3500.000000  3500.000000  3500.000000   
mean   1484.225714  8.067807e+06  1538.163143     7.602000     4.197714   
std     852.423418  4.984973e+06   416.264178     3.803196     4.782410   
min       0.000000  3.800000e+06  1019.000000     1.000000     1.000000   
25%     737.750000  4.800000e+06  1200.000000     5.000000     1.000000   
50%    1492.000000  6.600000e+06  1543.000000     5.000000     3.000000   
75%    2218.250000  1.050000e+07  1784.000000    10.000000     4.000000   
max    2944.000000  4.750000e+07  4856.000000    15.000000    18.000000   

        totalFloor          bhk  
count  3500.000000  3500.000000  
mean      6.371429     4.197714  
std       4.461808     4.782410  
min       4.000000     1.000000  
25%       4.000000     1.000000  
50%       4.000000     3.000000  
75%       5.000000     4.000000  
max      29.000000    18.000000

In [46]:
x=df[["sqft","floor","bhk"]]
y=df[["price"]]

In [47]:
x_train,x_test,y_train,y_test = train_test_split(x,y) 

In [48]:
x_train.shape

(2625, 3)

In [49]:
x_train

sqft  floor  bhk
980   1330      1    1
1320  1019      2    2
1334  1200      1    1
549   1784     18   18
1112  1857      4    4
...    ...    ...  ...
3485  1330      1    1
1079  1672      6    6
1357  1543      3    3
2768  1330      1    1
1115  1330      1    1

[2625 rows x 3 columns]

In [50]:
y_train.shape

(2625, 1)

In [51]:
y_train

price
980    7350000
1320   3800000
1334   4800000
549    7900000
1112  10500000
...        ...
3485   7350000
1079  15000000
1357   4025000
2768   7350000
1115   7350000

[2625 rows x 1 columns]

In [52]:
x_test.shape

(875, 3)

In [53]:
y_test.shape

(875, 1)

In [54]:
y_test

price
1634   6300000
2210   4900000
2332   4025000
152    7900000
1133   7900000
...        ...
2421   6300000
3141   3800000
2338   4800000
2341  15000000
1029  10500000

[875 rows x 1 columns]

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
model = LinearRegression()  #y=mX+c (formula for linear regression)
model

LinearRegression()

In [57]:
model.fit(x_train,y_train)

LinearRegression()

In [58]:
predict=model.predict(x_test)
predict

array([[ 7250968.27444796],
       [ 3941438.55787691],
       [ 8106862.35714942],
       [10233706.88402907],
       [10233706.88402907],
       [ 9291974.47467257],
       [ 4900277.64280434],
       [ 6122636.77125902],
       [14190449.71184311],
       [ 3941438.55787691],
       [ 9291974.47467257],
       [ 6122636.77125902],
       [ 7250968.27444796],
       [ 6122636.77125902],
       [ 7250968.27444796],
       [ 3189096.20935937],
       [ 7250968.27444796],
       [ 6122636.77125902],
       [ 6122636.77125902],
       [10233706.88402907],
       [ 7250968.27444796],
       [ 3941438.55787691],
       [14190449.71184311],
       [ 4900277.64280434],
       [11050048.37435882],
       [ 6122636.77125902],
       [ 8106862.35714942],
       [10233706.88402907],
       [ 7250968.27444796],
       [14190449.71184311],
       [10233706.88402907],
       [11050048.37435882],
       [ 6122636.77125902],
       [ 4900277.64280434],
       [ 9291974.47467257],
       [10233706.884

In [59]:
y_test

price
1634   6300000
2210   4900000
2332   4025000
152    7900000
1133   7900000
...        ...
2421   6300000
3141   3800000
2338   4800000
2341  15000000
1029  10500000

[875 rows x 1 columns]

In [60]:
model.intercept_

array([-6373755.97295007])

In [61]:
model.coef_

array([[ 9402.76252657, -4640.70806749, -4640.70806749]])

In [62]:
x_test

sqft  floor  bhk
1634  1450      1    1
2210  1100      3    3
2332  1543      3    3
152   1784     18   18
1133  1784     18   18
...    ...    ...  ...
2421  1450      1    1
3141  1019      2    2
2338  1200      1    1
2341  1672      6    6
1029  1857      4    4

[875 rows x 3 columns]

In [65]:
# visulization
import matplotlib.pyplot as plt
plt.scatter(y_test,predict1)
plt.show()

NameError: name 'predict1' is not defined

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
# r2 score
r2_score(predict,y_test)

In [ ]:
# mean absolut error
mean_absolute_error(y_test,predict)

In [ ]:
#mean squared error
mean_squared_error(y_test,predict)