In [1]:
import numpy
numpy.__version__

'1.26.4'

In [2]:
import numpy as np
df=np.array([10,20,30])
print(df)

[10 20 30]


In [5]:
import numpy as np
x=np.array([9,10])
y=np.array([7,8])
print(np.dot(x,y))

143


In [6]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [7]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

1
(9,)
9
int32


In [9]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [24]:
l1=[1,2,3]
l2=[4,5,6]
c1=np.array(l1)
c2=np.array(l2)
print(c1)
print(c2)

[1 2 3]
[4 5 6]


In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((3, 3))

array([[0.37404732, 0.75910026, 0.64976269],
       [0.62579924, 0.9935335 , 0.87598318],
       [0.20351897, 0.39907653, 0.47390254]])

In [18]:
np.random.randint(0, 10, (3, 3))

array([[0, 2, 2],
       [7, 3, 0],
       [3, 1, 5]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
x=np.arange(10,60,2)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

1
(25,)
25
int32


In [36]:
x=np.arange(10)
print(x[0])
print(x[2])
print(x[9])


0
2
9


In [37]:
x=np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x[:5]

array([0, 1, 2, 3, 4])

In [39]:
x[4:7]

array([4, 5, 6])

In [40]:
x[::2]

array([0, 2, 4, 6, 8])

In [41]:
x[1::2]

array([1, 3, 5, 7, 9])

In [42]:
x[::2]

array([0, 2, 4, 6, 8])

In [43]:
x[5::-2]

array([5, 3, 1])

In [44]:
x2=np.random.randint(0,12,(3,4))

In [45]:
x2[:2,:3]

array([[ 7, 10,  9],
       [ 3,  7,  9]])

In [46]:
grid = np.arange(1, 10).reshape((3, 3))

print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
x=np.array([1,2,3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [48]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [49]:
x=np.array([1,2,3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [50]:
z=[99,99,99]

print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [51]:
upper, lower = np.vsplit(grid, [2])

print(upper)
print(lower)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [52]:
upper, lower = np.hsplit(grid, [2])

print(upper)
print(lower)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [53]:
x=np.array([-2,-1,0,1,2])

abs(x)

array([2, 1, 0, 1, 2])

In [54]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [55]:
A=np.array([1,0,1,0,1,0],dtype=bool)

B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [56]:
In[37]:A=np.array([1,0,1,0,1,0],dtype=bool)

B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()